# Generated by Django 4.2.20 on 2025-03-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                max_length=20,
            ),
        ),
    ]
