# Generated by Django 4.2.20 on 2025-03-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_transaction_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="from_account",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="to_account",
        ),
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="account_transactions",
                to="wallet.account",
            ),
        ),
    ]
